import {StyleSheet} from 'react-native';
import {colors} from '../../../config/theme';
import {responsiveSize} from '../../../utils/responsiveFontSize';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.themeBgColor,
  },
  clientsList: {
    paddingBottom: 20,
    paddingTop: 20,
  },
  caseCardContainer: {
    shadowColor: colors.themeBgColor,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 0.5,
    shadowRadius: 3.5,
    borderRadius: 12,
    marginVertical: 10,
    paddingHorizontal: 15,
    alignSelf: 'center',
    elevation: 10,
  },
  caseGradient: {
    justifyContent: 'space-around',
    borderRadius: 12,
    width: '100%',
  },
  AppointmentNotifitionBox: {
    width: '100%',
    borderRadius: 8,
    padding: 15,
  },
  caseHeader: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  Appointment: {
    fontSize: responsiveSize(16),
    color: colors.white,
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRadius: 8,
    paddingVertical: 4,
  },
  AppointmentTime: {
    fontSize: responsiveSize(12),
    marginLeft: 5,
    color: 'white',
  },
  AppointmentTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    rowGap: 10,
    paddingTop: 20,
    paddingBottom: 5,
    marginRight: 20,
  },
  Appointmentwith: {
    flexDirection: 'row',
    backgroundColor: colors.textViewBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  paidContainer: {
    flexDirection: 'row',
    backgroundColor: colors.textViewBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  Appointmenttype: {
    flexDirection: 'row',
    backgroundColor: '#EB5757',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  amountLabel: {
    color: colors.white,
    fontSize: responsiveSize(12),
    textAlign: 'left',
  },
  amountValue: {
    color: colors.white,
    fontSize: responsiveSize(12),
    fontWeight: '700',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingIndicator: {
    paddingVertical: 20,
  },
  noDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataText: {
    color: colors.gray,
    fontSize: responsiveSize(16),
    textAlign: 'center',
  },

  searchContainer: {
    width: '100%',
    paddingHorizontal: 15,
    marginTop: 30,
    marginBottom:10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: colors.bottomTabLightGray,
    borderWidth: 1,
    borderColor: colors.inputBorderColor,
    borderRadius: 8,
    height: 42,
  },
  searchIcon: {
    height: 24,
    width: 24,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 10,
    fontSize: responsiveSize(12),
    fontWeight: '400',
    color: colors.white,
  },
  searchTypeButtonContainer: {
    // flex: 0.33,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: colors.bottomTabLightGray,
    borderWidth: 1,
    borderColor: colors.inputBorderColor,
    borderRadius: 8,
    height: 42,
  },
  searchTypeButtonText: {
    fontSize: responsiveSize(12),
    color: colors.white,
    paddingRight: 10,
  },
  dropdownIcon: {
    height: 12,
    width: 12,
    tintColor: colors.white,
  },
  bottomSheetBackground: {
    backgroundColor: colors.bottomTabSignOut,
  },
  bottomSheetHandle: {
    backgroundColor: '#ccc',
    width: 40,
  },

  selectorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 24,
    marginTop: 10,
    gap: 8,
  },
  searchTypeSelectorBtn: {
    bottom: Platform.OS === 'android' ? 10 : 15,
  },
  pillButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  selectedPill: {
    backgroundColor: colors.textGrayTwo,
    borderRadius: 25,
    borderColor: colors.textGrayTwo,
    borderWidth: 1,
    elevation: 1,
    shadowColor: colors.white,
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  pillText: {
    color: colors.gray,
    fontSize: 14,
    fontFamily: 'Inter-Medium',
  },
  selectedPillText: {
    color: 'white',
    fontWeight: '600',
  },
});
