export const AppImages = {
    themeOne : require('../../assets/themeOne.jpeg'),
    themeTwo : require('../../assets/themeTwo.jpeg'),
    themeThree : require('../../assets/themeThree.jpeg'),
    themeFour : require('../../assets/themeFour.jpeg'),
    themeFive : require('../../assets/themeFive.jpeg'),
    themeSix : require('../../assets/themeSix.jpeg'),
    themeSeven : require('../../assets/themeSeven.jpeg'),
    addIcon : require('../../assets/add.png'),
    refreshIcon: require('../../assets/refreshIcon.png'),
    loginTheme: require('../../assets/loginTheme.png'),
    backArrow: require('../../assets/backArrow.png'),
    appLogo: require('../../assets/appLogo.png'),
    mail: require('../../assets/mail.png'),
    key: require('../../assets/key.png'),
    eye: require('../../assets/eye.png'),
    hide: require('../../assets/hide.png'),
    show: require('../../assets/show.png'),
}